# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

require_relative 'controller_test_base'

class CardControllerTest < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.card
    @response_catcher = @controller.http_call_back
  end

  # This API allows to fetch details of a single fuel card from the Shell Card Platform. If a **CardId** request parameter is provided, this will return a single card.  If a **PAN** request parameter is provided, this may result in multiple fuel cards matching the search criteria. The card details of the most recently issued card will be returned.
  #
  #  #### Supported operations
  #  * Get card by card id or PAN or PANID
  def test_card_details
    # Parameters for the API call
    request_id = '233e4567-e89b-12d3-a456-426614174000'
    body = CardDetailsReq.from_hash(APIHelper.json_deserialize(
      '{"Filters":{"PayerNumber":"CZ00000927","AccountNumber":"CZ00000927","Co'\
      'lCoCode":32,"PAN":"7002327340223080230"}}', false))

    # Perform the API call through the SDK function
    result = @controller.card_details(request_id, body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json; charset=utf-8'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"Data":[{"AccountId":1227,"AccountNumber":"CZ00000927","AccountShortNa'\
      'me":"Dominica1_1","BundleId":null,"CardBlockSchedules":null,"CardDelive'\
      'ryAddress":{"AddressId":297845,"AddressLine1":"1 Elgin Street","Address'\
      'Line2":"Acropolis","AddressLine3":"","City":"Athens Αθήνα","CompanyName'\
      '":"Dominica1_C","ContactForeName":"","ContactLastName":"","ContactMiddl'\
      'eName":"","ContactTitle":"","Country":"Czech Republic","CountryId":5,"C'\
      'ountryISOCode":"CZ","Region":"","RegionId":null,"ZipCode":"123 45"},"Ca'\
      'rdGroupId":null,"CardGroupName":null,"CardId":463497,"CardTypeCode":"70'\
      '02327","CardTypeId":106,"CardTypeName":"CZ FLT INT MUL LEA R7","ColCoCo'\
      'untryCode":"CZ","DriverName":"SHELL CARD1","EmbossText":"DOMINICA1","Ex'\
      'piryDate":"20241031","FleetIdPrompt":false,"FuelSets":[{"Description":"'\
      'Restrictions no longer supported here","ProductRestrictionId":510}],"Ha'\
      'sPIN":true,"InternationalPOSLanguageCode":"eng","InternationalPOSLangua'\
      'geID":8,"IsChipCard":true,"IsCRT":false,"IsFleet":true,"IsInternational'\
      '":true,"IsMagStripCard":true,"IsNational":false,"IsPartnerSitesIncluded'\
      '":true,"IsSelfSelectedPIN":false,"IsShellSitesOnly":false,"IssuedDate":'\
      '"20201023","IssueNumber":1,"IsVirtualCard":false,"LastModifiedDate":"20'\
      '230620 13:30:30","LastUsedDate":null,"LocalCurrencyCode":"CZK","LocalCu'\
      'rrencySymbol":"Kč","LocalPOSLanguageCode":"ces","LocalPOSLanguageID":5,'\
      '"MisuseDate":null,"NonFuelSets":null,"OdometerPrompt":false,"PAN":"7002'\
      '327340223080230","PayerId":1227,"PayerNumber":"CZ00000927","PermanentBl'\
      'ockAllowed":false,"PINDeliveryAddress":{"AddressId":269053,"AddressLine'\
      '1":"1 Elgin Street","AddressLine2":"Acropolis","AddressLine3":"","City"'\
      ':"Athens Αθήνα","CompanyName":"Dominica1_C","ContactForeName":"","Conta'\
      'ctLastName":"","ContactMiddleName":"","ContactTitle":"","Country":"Czec'\
      'h Republic","CountryId":5,"CountryISOCode":"CZ","Region":"","RegionId":'\
      '0,"ZipCode":"123 45"},"PINType":"Card","PurchaseCategoryCode":"0","Purc'\
      'haseCategoryId":100,"PurchaseCategoryName":"0 - Diesel Products and TMF'\
      '","ReissueSetting":"True","RenewalDate":"20240703","RenewedCardExpiryDa'\
      'te":null,"RenewedCardId":null,"RenewedCardIssueNumber":null,"RenewedCar'\
      'dReissueSetting":"","RenewedCardStatus":"","RenewedCardStatusId":null,"'\
      'Status":"Blocked Card","StatusId":7,"Temperature":"10-Warm","TemporaryB'\
      'lockAllowed":false,"TokenTypeId":108,"UnblockAllowed":false,"VRN":"SH12'\
      '3456","TokenTypeName":"CZ FLT Int Lease Plan Multi - CHIP","CreationDat'\
      'e":"20201022 14:55:06","EffectiveDate":"20201022","IsPartnerCard":false'\
      ',"ClientReferenceId":"","CardPANID":17240713,"IsEMVContact":false,"IsEM'\
      'VContactless":false,"IsRFID":false,"RequirePIN":true,"OfflinePIN":false'\
      ',"PINChangeSupported":true,"PINAdviceTypeID":1,"CardMediaCode":"100999"'\
      ',"MediumTypeID":1,"MediumType":"Fuel Card","PANID":17240713,"MaskedPAN"'\
      ':"7002327******080230"}],"RequestId":"233e4567-e89b-12d3-a456-426614174'\
      '000","Status":"SUCCESS"}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

  # This API allows to move one or more fuel cards (up to 500) across card groups within a single account or across accounts under the same payer. If the API call succeeds, the API will return a reference number and queue the request for asynchronous processing.
  ##### Supported operations
  #  * Moving card to exisitng card group
  #  * Moving card to new card group
  #  * Removing a card from a card group 
  #
  ##### Validation rules
  #  * Number of cards per request does not exceed 500
  #  * Given **PANID** or **PAN** for a card matches with only one card
  #  * A card is allowed to be moved to the **TargetCardGroupId** or **TargetAccountNumber**
  #  * A pending move request does not exist in the queue for a card submitted on the same date (customers local)
  #  * A card has not been moved as part of a previous request on the same date (customers local)
  #
  ##### API response 
  #  * A main reference number for the API request (**MoveCardRequestReference**)
  #  * Individual reference numbers (**MoveCardReference**) for each card move request that passes validation  
  #  * A list of cards (**ErrorCards**) that failed validation along with the appropriate error code and message
  #
  ##### Asynchronous processing of valid API request 
  #  * Move card requests that have been submitted and processed will be reflected after midnight according to the customers local date
  #
  def test_card_move
    # Parameters for the API call
    request_id = '233e4567-e89b-12d3-a456-426614174000'
    body = CardMoveRequest.from_hash(APIHelper.json_deserialize(
      '{"ColCoCode":32,"PayerNumber":"CZ00000927","Cards":[{"AccountNumber":"C'\
      'Z00000927","CardId":466251}],"TargetAccountNumber":"CZ00000927","Target'\
      'CardGroupId":3228,"TargetNewCardGroupName":"DEMORE1"}', false))

    # Perform the API call through the SDK function
    result = @controller.card_move(request_id, body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json; charset=utf-8'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"RequestId":"233e4567-e89b-12d3-a456-426614174000","MainReference":559'\
      '063,"Status":"SUCCESS","Data":[{"MoveCardReference":"11793","AccountId"'\
      ':"1227","AccountNumber":"CZ00000927","CardId":"466251","PAN":"700232904'\
      '0232160159"}]}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

end