# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # HTTP Methods Enumeration.
  class HttpMethodEnum < CoreLibrary::HttpMethod
  end
end
