# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
