# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
