# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
