# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # AccountRestrictionResponse Model.
  class AccountRestrictionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # API Request Id
    # @return [String]
    attr_accessor :request_id

    # API Response Status
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['request_id'] = 'RequestId'
      @_hash['status'] = 'Status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        request_id
        status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(request_id = SKIP,
                   status = SKIP)
      @request_id = request_id unless request_id == SKIP
      @status = status unless status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      request_id = hash.key?('RequestId') ? hash['RequestId'] : SKIP
      status = hash.key?('Status') ? hash['Status'] : SKIP

      # Create object from extracted values.
      AccountRestrictionResponse.new(request_id,
                                     status)
    end
  end
end
