# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # Whether to reissue card automatically when nearing the expiry.  Allowed
  # values: - 1.    As per card type setting (Default). 2.    Card will be
  # Reissued when nearing its expiry date. 3.    Card will not be Reissued.
  class CardDetailAutoRenewEnum
    CARD_DETAIL_AUTO_RENEW_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CARD_DETAIL_AUTO_RENEW_ENUM.include?(value)
    end
  end
end
