# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # Response entity object for CardBlockSchedule  list
  class CardBlockSchedule < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Effective start date of Block / Unblock<br />
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :from_date

    # Effective end date of Block / Unblock<br />
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :to_date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['from_date'] = 'FromDate'
      @_hash['to_date'] = 'ToDate'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        from_date
        to_date
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        from_date
        to_date
      ]
    end

    def initialize(from_date = SKIP, to_date = SKIP)
      @from_date = from_date unless from_date == SKIP
      @to_date = to_date unless to_date == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      from_date = hash.key?('FromDate') ? hash['FromDate'] : SKIP
      to_date = hash.key?('ToDate') ? hash['ToDate'] : SKIP

      # Create object from extracted values.
      CardBlockSchedule.new(from_date,
                            to_date)
    end
  end
end
