# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # PIN type:   * `Card` - Card PIN   * `Fleet` - Fleet PIN
  class CardDetailsResponsePINTypeEnum
    CARD_DETAILS_RESPONSE_PIN_TYPE_ENUM = [
      # TODO: Write general description for CARD
      CARD = 'Card'.freeze,

      # TODO: Write general description for FLEET
      FLEET = 'Fleet'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CARD_DETAILS_RESPONSE_PIN_TYPE_ENUM.include?(value)
    end
  end
end
