# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # PIN type:   * `Card` - Card PIN   * `Fleet` - Fleet PIN
  class CardDetailsResponsePINTypeEnum
    CARD_DETAILS_RESPONSE_PIN_TYPE_ENUM = [
      # TODO: Write general description for CARD
      CARD = 'Card'.freeze,

      # TODO: Write general description for FLEET
      FLEET = 'Fleet'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CARD_DETAILS_RESPONSE_PIN_TYPE_ENUM.include?(value)
    end

    def self.from_value(value, default_value = CARD)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'card' then CARD
      when 'fleet' then FLEET
      else
        default_value
      end
    end
  end
end
