# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # Whether to reissue card automatically when nearing the expiry.  Allowed
  # values: - 1.    As per card type setting (Default). 2.    Card will be
  # Reissued when nearing its expiry date. 3.    Card will not be Reissued.
  class CardDetailAutoRenewEnum
    CARD_DETAIL_AUTO_RENEW_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CARD_DETAIL_AUTO_RENEW_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ENUM_1)
      return default_value if value.nil?

      str = value.to_s.strip
      if str.match?(/\A\d+\z/)
        num = str.to_i
        return num if CARD_DETAIL_AUTO_RENEW_ENUM.include?(num)

        return default_value
      end

      case str.downcase
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      when 'enum_3' then ENUM_3
      else
        default_value
      end
    end
  end
end
