# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # Reissue setting of the renewed new card. Reissue Setting:   * `True` - Card
  # will be sent to production   * `False` - Parent Card is Dormant or the Card
  # is not to be produced
  class CardDetailsResponseRenewedCardReissueSettingEnum
    CARD_DETAILS_RESPONSE_RENEWED_CARD_REISSUE_SETTING_ENUM = [
      # TODO: Write general description for TRUE
      TRUE = 'True'.freeze,

      # TODO: Write general description for FALSE
      FALSE = 'False'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CARD_DETAILS_RESPONSE_RENEWED_CARD_REISSUE_SETTING_ENUM.include?(value)
    end

    def self.from_value(value, default_value = TRUE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'true' then TRUE
      when 'false' then FALSE
      else
        default_value
      end
    end
  end
end
