# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # CardSummaryRequest Model.
  class CardSummaryRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Encapsulates the details of a Summary Request.
    # Summary Request fields are same as the Search Request base class and no
    # new fields are required.
    # @return [SummaryRequest]
    attr_accessor :filters

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['filters'] = 'Filters'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        filters
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(filters = SKIP)
      @filters = filters unless filters == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      filters = SummaryRequest.from_hash(hash['Filters']) if hash['Filters']

      # Create object from extracted values.
      CardSummaryRequest.new(filters)
    end
  end
end
