# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # CreateCardGroupResponseErrorCardsItems Model.
  class CreateCardGroupResponseErrorCardsItems < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Card Id of the card.
    # @return [Integer]
    attr_accessor :card_id

    # PAN of the card.
    # @return [String]
    attr_accessor :pan

    # Error code for validation failure.
    # @return [String]
    attr_accessor :error_code

    # Description of validation failure.
    # @return [String]
    attr_accessor :error_description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_id'] = 'CardId'
      @_hash['pan'] = 'PAN'
      @_hash['error_code'] = 'ErrorCode'
      @_hash['error_description'] = 'ErrorDescription'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        card_id
        pan
        error_code
        error_description
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(card_id = SKIP,
                   pan = SKIP,
                   error_code = SKIP,
                   error_description = SKIP)
      @card_id = card_id unless card_id == SKIP
      @pan = pan unless pan == SKIP
      @error_code = error_code unless error_code == SKIP
      @error_description = error_description unless error_description == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP
      pan = hash.key?('PAN') ? hash['PAN'] : SKIP
      error_code = hash.key?('ErrorCode') ? hash['ErrorCode'] : SKIP
      error_description =
        hash.key?('ErrorDescription') ? hash['ErrorDescription'] : SKIP

      # Create object from extracted values.
      CreateCardGroupResponseErrorCardsItems.new(card_id,
                                                 pan,
                                                 error_code,
                                                 error_description)
    end
  end
end
