# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # CreateBundleResponseDataItemsCardsItems Model.
  class CreateBundleResponseDataItemsCardsItems < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Card PAN.
    # @return [String]
    attr_accessor :pan

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pan'] = 'PAN'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pan
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pan = SKIP)
      @pan = pan unless pan == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pan = hash.key?('PAN') ? hash['PAN'] : SKIP

      # Create object from extracted values.
      CreateBundleResponseDataItemsCardsItems.new(pan)
    end
  end
end
