# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # Datum Model.
  class Datum < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Card Id.
    # @return [Integer]
    attr_accessor :card_id

    # PAN of the card.
    # @return [String]
    attr_accessor :card_pan

    # Account id
    # @return [Integer]
    attr_accessor :account_id

    # Account number
    # @return [String]
    attr_accessor :account_number

    # Individual delivery address update reference number for the delivery
    # address update request.
    # @return [Integer]
    attr_accessor :reference_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_id'] = 'CardId'
      @_hash['card_pan'] = 'CardPAN'
      @_hash['account_id'] = 'AccountId'
      @_hash['account_number'] = 'AccountNumber'
      @_hash['reference_id'] = 'ReferenceId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        card_id
        card_pan
        account_id
        account_number
        reference_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        card_id
        card_pan
        account_id
      ]
    end

    def initialize(card_id = SKIP, card_pan = SKIP, account_id = SKIP,
                   account_number = SKIP, reference_id = SKIP)
      @card_id = card_id unless card_id == SKIP
      @card_pan = card_pan unless card_pan == SKIP
      @account_id = account_id unless account_id == SKIP
      @account_number = account_number unless account_number == SKIP
      @reference_id = reference_id unless reference_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP
      card_pan = hash.key?('CardPAN') ? hash['CardPAN'] : SKIP
      account_id = hash.key?('AccountId') ? hash['AccountId'] : SKIP
      account_number = hash.key?('AccountNumber') ? hash['AccountNumber'] : SKIP
      reference_id = hash.key?('ReferenceId') ? hash['ReferenceId'] : SKIP

      # Create object from extracted values.
      Datum.new(card_id,
                card_pan,
                account_id,
                account_number,
                reference_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} card_id: #{@card_id}, card_pan: #{@card_pan}, account_id: #{@account_id},"\
      " account_number: #{@account_number}, reference_id: #{@reference_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} card_id: #{@card_id.inspect}, card_pan: #{@card_pan.inspect}, account_id:"\
      " #{@account_id.inspect}, account_number: #{@account_number.inspect}, reference_id:"\
      " #{@reference_id.inspect}>"
    end
  end
end
