# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # DayTimeRestrictions Model.
  class DayTimeRestrictions < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # True if card could be used on a Monday, else false
    # @return [TrueClass | FalseClass]
    attr_accessor :monday

    # True if card could be used on a Tuesday, else false.
    # @return [TrueClass | FalseClass]
    attr_accessor :tuesday

    # True if card could be used on a Wednesday, else false.
    # @return [TrueClass | FalseClass]
    attr_accessor :wednesday

    # True if card could be used on a Thursday, else false
    # @return [TrueClass | FalseClass]
    attr_accessor :thursday

    # True if card could be used on a Friday, else false
    # @return [TrueClass | FalseClass]
    attr_accessor :friday

    # True if card could be used on a Saturday, else false
    # @return [TrueClass | FalseClass]
    attr_accessor :saturday

    # True if card could be used on a Sunday, else false.
    # @return [TrueClass | FalseClass]
    attr_accessor :sunday

    # Card could be used from this time in a day.
    # Format: HH:mm (24-hour format)
    # Note: 
    # 1.    Clients to convert this to appropriate DateTime or TimeSpan type.
    # “00:00” is the lowest time value and “23:59” is the highest time value.
    # @return [String]
    attr_accessor :time_from

    # Card could be used up to this time in a day. 
    # Format: HH:mm (24-hour format)
    # Note: 
    # 1.    Clients to convert this to appropriate DateTime or TimeSpan type. 
    # “00:00” is the lowest time value and “23:59” is the highest time value.
    # @return [String]
    attr_accessor :time_to

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['monday'] = 'Monday'
      @_hash['tuesday'] = 'Tuesday'
      @_hash['wednesday'] = 'Wednesday'
      @_hash['thursday'] = 'Thursday'
      @_hash['friday'] = 'Friday'
      @_hash['saturday'] = 'Saturday'
      @_hash['sunday'] = 'Sunday'
      @_hash['time_from'] = 'TimeFrom'
      @_hash['time_to'] = 'TimeTo'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        monday
        tuesday
        wednesday
        thursday
        friday
        saturday
        sunday
        time_from
        time_to
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(monday = SKIP, tuesday = SKIP, wednesday = SKIP,
                   thursday = SKIP, friday = SKIP, saturday = SKIP,
                   sunday = SKIP, time_from = SKIP, time_to = SKIP)
      @monday = monday unless monday == SKIP
      @tuesday = tuesday unless tuesday == SKIP
      @wednesday = wednesday unless wednesday == SKIP
      @thursday = thursday unless thursday == SKIP
      @friday = friday unless friday == SKIP
      @saturday = saturday unless saturday == SKIP
      @sunday = sunday unless sunday == SKIP
      @time_from = time_from unless time_from == SKIP
      @time_to = time_to unless time_to == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      monday = hash.key?('Monday') ? hash['Monday'] : SKIP
      tuesday = hash.key?('Tuesday') ? hash['Tuesday'] : SKIP
      wednesday = hash.key?('Wednesday') ? hash['Wednesday'] : SKIP
      thursday = hash.key?('Thursday') ? hash['Thursday'] : SKIP
      friday = hash.key?('Friday') ? hash['Friday'] : SKIP
      saturday = hash.key?('Saturday') ? hash['Saturday'] : SKIP
      sunday = hash.key?('Sunday') ? hash['Sunday'] : SKIP
      time_from = hash.key?('TimeFrom') ? hash['TimeFrom'] : SKIP
      time_to = hash.key?('TimeTo') ? hash['TimeTo'] : SKIP

      # Create object from extracted values.
      DayTimeRestrictions.new(monday,
                              tuesday,
                              wednesday,
                              thursday,
                              friday,
                              saturday,
                              sunday,
                              time_from,
                              time_to)
    end
  end
end
