# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # An entity that encapsulate the country restrictions. Optional.
  class LocationRestrictionsCountryRestrictions < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Boolean	Flag indicates whether the profile is inclusive or exclusive.
    # Mandatory
    # Example: False - (inclusive), i.e. the “Countries” property lists the
    # countries where the transactions will be allowed.
    # True - (exclusive), i.e. the “Countries” property lists the countries
    # where the transactions will be declined.
    # @return [TrueClass | FalseClass]
    attr_accessor :exclusive

    # ISO 3166-1 Numeric-3 code of the country where the network restriction is
    # applied.
    # Example: 826 for United Kingdom.
    # Mandatory
    # @return [Array[String]]
    attr_accessor :countries

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['exclusive'] = 'Exclusive'
      @_hash['countries'] = 'Countries'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(exclusive = nil,
                   countries = nil)
      @exclusive = exclusive
      @countries = countries
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      exclusive = hash.key?('Exclusive') ? hash['Exclusive'] : nil
      countries = hash.key?('Countries') ? hash['Countries'] : nil

      # Create object from extracted values.
      LocationRestrictionsCountryRestrictions.new(exclusive,
                                                  countries)
    end
  end
end
