# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # Type of the reference number provided.<br /> Mandatory if ReferenceNumber is
  # provided. Else optional.<br /> Allowed Values:<br /> 1=Main Reference(Main
  # Order Reference Number returned in the output of Card/OrderCard service. <br
  # /> 2=Order Card Reference (Reference number for each individual card in the
  # order submitted via Card/OrderCard service. <br /> 3=Bulk Order Card
  # Reference (Reference number returned in the response of bulkcardinterface
  # /UploadOrderCardTemplate. )
  class OrderCardEnquiryReqReferenceTypeEnum
    ORDER_CARD_ENQUIRY_REQ_REFERENCE_TYPE_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ORDER_CARD_ENQUIRY_REQ_REFERENCE_TYPE_ENUM.include?(value)
    end
  end
end
