# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # This class holds the PIN Reminder References
  class PINReminderReference < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Card Id
    # @return [Integer]
    attr_accessor :card_id

    # PAN ID
    # @return [Integer]
    attr_accessor :panid

    # PAN
    # @return [Integer]
    attr_accessor :pan

    # Expiry date of the card.
    # Mandatory if Either PAN or PANID is passed, else optional.
    # Format: yyyyMMdd
    # @return [String]
    attr_accessor :card_expiry_date

    # Individual card pin reminder reference number for the Pin Reminder
    # request.
    # @return [Integer]
    attr_accessor :reference_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_id'] = 'CardId'
      @_hash['panid'] = 'PANID'
      @_hash['pan'] = 'PAN'
      @_hash['card_expiry_date'] = 'CardExpiryDate'
      @_hash['reference_id'] = 'ReferenceId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        card_id
        panid
        pan
        card_expiry_date
        reference_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        card_id
        panid
        pan
        card_expiry_date
      ]
    end

    def initialize(card_id = SKIP,
                   panid = SKIP,
                   pan = SKIP,
                   card_expiry_date = SKIP,
                   reference_id = SKIP)
      @card_id = card_id unless card_id == SKIP
      @panid = panid unless panid == SKIP
      @pan = pan unless pan == SKIP
      @card_expiry_date = card_expiry_date unless card_expiry_date == SKIP
      @reference_id = reference_id unless reference_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP
      panid = hash.key?('PANID') ? hash['PANID'] : SKIP
      pan = hash.key?('PAN') ? hash['PAN'] : SKIP
      card_expiry_date =
        hash.key?('CardExpiryDate') ? hash['CardExpiryDate'] : SKIP
      reference_id = hash.key?('ReferenceId') ? hash['ReferenceId'] : SKIP

      # Create object from extracted values.
      PINReminderReference.new(card_id,
                               panid,
                               pan,
                               card_expiry_date,
                               reference_id)
    end
  end
end
