# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # ProductAllOf0 Model.
  class ProductAllOf0 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The productCode returned by the Gateway API.
    # Example: 021
    # @return [String]
    attr_accessor :global_product_code

    # The description returned by the Gateway API.
    # @return [String]
    attr_accessor :description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['global_product_code'] = 'GlobalProductCode'
      @_hash['description'] = 'Description'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      %w[
        global_product_code
        description
      ]
    end

    def initialize(global_product_code = nil, description = nil)
      @global_product_code = global_product_code
      @description = description
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      global_product_code =
        hash.key?('GlobalProductCode') ? hash['GlobalProductCode'] : nil
      description = hash.key?('Description') ? hash['Description'] : nil

      # Create object from extracted values.
      ProductAllOf0.new(global_product_code,
                        description)
    end
  end
end
