# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # PurchaseCategoryResponse Model.
  class PurchaseCategoryResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[PurchaseCategory1AllOf0]]
    attr_accessor :purchase_categories

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['purchase_categories'] = 'PurchaseCategories'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        purchase_categories
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(purchase_categories = SKIP)
      @purchase_categories = purchase_categories unless purchase_categories == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      purchase_categories = nil
      unless hash['PurchaseCategories'].nil?
        purchase_categories = []
        hash['PurchaseCategories'].each do |structure|
          purchase_categories << (PurchaseCategory1AllOf0.from_hash(structure) if structure)
        end
      end

      purchase_categories = SKIP unless hash.key?('PurchaseCategories')

      # Create object from extracted values.
      PurchaseCategoryResponse.new(purchase_categories)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} purchase_categories: #{@purchase_categories}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} purchase_categories: #{@purchase_categories.inspect}>"
    end
  end
end
