# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # ResponseDeliveryAddressUpdate Model.
  class ResponseDeliveryAddressUpdate < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Mandatory UUID (according to RFC 4122 standards) for requests and
    # responses. This will be played back in the response from the requests.
    # @return [UUID | String]
    attr_accessor :request_id

    # Mandatory UUID (according to RFC 4122 standards) for requests and
    # responses. This will be played back in the response from the requests.
    # @return [DeliveryAddressUpdateStatusEnum]
    attr_accessor :status

    # Main reference number for tracking.
    # @return [Integer]
    attr_accessor :main_reference

    # List of Delivery address update entity. The fields of this entity are
    # described below.
    # @return [Array[Datum]]
    attr_accessor :data

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['request_id'] = 'RequestId'
      @_hash['status'] = 'Status'
      @_hash['main_reference'] = 'MainReference'
      @_hash['data'] = 'Data'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        main_reference
        data
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(request_id = nil, status = nil, main_reference = SKIP,
                   data = SKIP)
      @request_id = request_id
      @status = status
      @main_reference = main_reference unless main_reference == SKIP
      @data = data unless data == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      request_id = hash.key?('RequestId') ? hash['RequestId'] : nil
      status = hash.key?('Status') ? hash['Status'] : nil
      main_reference = hash.key?('MainReference') ? hash['MainReference'] : SKIP
      # Parameter is an array, so we need to iterate through it
      data = nil
      unless hash['Data'].nil?
        data = []
        hash['Data'].each do |structure|
          data << (Datum.from_hash(structure) if structure)
        end
      end

      data = SKIP unless hash.key?('Data')

      # Create object from extracted values.
      ResponseDeliveryAddressUpdate.new(request_id,
                                        status,
                                        main_reference,
                                        data)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} request_id: #{@request_id}, status: #{@status}, main_reference:"\
      " #{@main_reference}, data: #{@data}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} request_id: #{@request_id.inspect}, status: #{@status.inspect},"\
      " main_reference: #{@main_reference.inspect}, data: #{@data.inspect}>"
    end
  end
end
