# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # RestrictionCardRequest Model.
  class RestrictionCardRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Collecting Company Id of the selected payer. 
    # Optional if ColCoCode is passed else Mandatory.
    # Example:
    # 1 for Philippines
    # 5 for UK
    # @return [Integer]
    attr_accessor :col_co_id

    # Payer Number of the selected payer.
    # Optional if PayerId is passed else Mandatory
    # Example: GB000000123
    # List of restrictions to be applied on the card. The details of
    # CardRestriction entity is given below.
    # @return [String]
    attr_accessor :payer_number

    # Payer Id of the selected payer.
    # Optional if PayerNumber is passed else Mandatory
    # Example: 123456
    # @return [Integer]
    attr_accessor :payer_id

    # List of restrictions to be applied on the card. The details of
    # CardRestriction entity is given below.
    # @return [Array[RestrictionCardRequestCardsItems]]
    attr_accessor :cards

    # Collecting Company Code (Shell Code) of the selected payer. 
    # Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia,
    # Ukraine etc. It is optional for other countries if ColCoID is provided.
    # Example:
    # 86 for Philippines
    # 5 for UK
    # @return [Integer]
    attr_accessor :col_co_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['col_co_id'] = 'ColCoId'
      @_hash['payer_number'] = 'PayerNumber'
      @_hash['payer_id'] = 'PayerId'
      @_hash['cards'] = 'Cards'
      @_hash['col_co_code'] = 'ColCoCode'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        col_co_id
        payer_number
        payer_id
        cards
        col_co_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(col_co_id = SKIP,
                   payer_number = SKIP,
                   payer_id = SKIP,
                   cards = SKIP,
                   col_co_code = SKIP)
      @col_co_id = col_co_id unless col_co_id == SKIP
      @payer_number = payer_number unless payer_number == SKIP
      @payer_id = payer_id unless payer_id == SKIP
      @cards = cards unless cards == SKIP
      @col_co_code = col_co_code unless col_co_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      col_co_id = hash.key?('ColCoId') ? hash['ColCoId'] : SKIP
      payer_number = hash.key?('PayerNumber') ? hash['PayerNumber'] : SKIP
      payer_id = hash.key?('PayerId') ? hash['PayerId'] : SKIP
      # Parameter is an array, so we need to iterate through it
      cards = nil
      unless hash['Cards'].nil?
        cards = []
        hash['Cards'].each do |structure|
          cards << (RestrictionCardRequestCardsItems.from_hash(structure) if structure)
        end
      end

      cards = SKIP unless hash.key?('Cards')
      col_co_code = hash.key?('ColCoCode') ? hash['ColCoCode'] : SKIP

      # Create object from extracted values.
      RestrictionCardRequest.new(col_co_id,
                                 payer_number,
                                 payer_id,
                                 cards,
                                 col_co_code)
    end
  end
end
