# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # RestrictionSearchCardRequestFiltersCardsItems Model.
  class RestrictionSearchCardRequestFiltersCardsItems < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Card PAN.
    # Optional if CardId is given, else mandatory. 
    # Note: PAN is ignored if CardId is given.
    # @return [String]
    attr_accessor :pan

    # Unique Card Id in GFN.
    # Optional if PAN is given, else mandatory.
    # @return [Integer]
    attr_accessor :card_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pan'] = 'PAN'
      @_hash['card_id'] = 'CardId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        pan
        card_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(pan = SKIP,
                   card_id = SKIP)
      @pan = pan unless pan == SKIP
      @card_id = card_id unless card_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pan = hash.key?('PAN') ? hash['PAN'] : SKIP
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP

      # Create object from extracted values.
      RestrictionSearchCardRequestFiltersCardsItems.new(pan,
                                                        card_id)
    end
  end
end
