# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # SearchCardRestrictionRes Model.
  class SearchCardRestrictionRes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Request Id of the API call
    # @return [String]
    attr_accessor :request_id

    # Request Id of the API call
    # @return [Array[RestrictionCardList]]
    attr_accessor :cards

    # Request Id of the API call
    # @return [Restriction]
    attr_accessor :restrictions

    # Request Id of the API call
    # @return [ErrorStatus]
    attr_accessor :error

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['request_id'] = 'RequestId'
      @_hash['cards'] = 'cards'
      @_hash['restrictions'] = 'Restrictions'
      @_hash['error'] = 'Error'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        request_id
        cards
        restrictions
        error
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        request_id
      ]
    end

    def initialize(request_id = SKIP, cards = SKIP, restrictions = SKIP,
                   error = SKIP)
      @request_id = request_id unless request_id == SKIP
      @cards = cards unless cards == SKIP
      @restrictions = restrictions unless restrictions == SKIP
      @error = error unless error == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      request_id = hash.key?('RequestId') ? hash['RequestId'] : SKIP
      # Parameter is an array, so we need to iterate through it
      cards = nil
      unless hash['cards'].nil?
        cards = []
        hash['cards'].each do |structure|
          cards << (RestrictionCardList.from_hash(structure) if structure)
        end
      end

      cards = SKIP unless hash.key?('cards')
      restrictions = Restriction.from_hash(hash['Restrictions']) if hash['Restrictions']
      error = ErrorStatus.from_hash(hash['Error']) if hash['Error']

      # Create object from extracted values.
      SearchCardRestrictionRes.new(request_id,
                                   cards,
                                   restrictions,
                                   error)
    end
  end
end
