# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # SubmittedMoveCard Model.
  class SubmittedMoveCard < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_number

    # Card Id of the card.
    # @return [String]
    attr_accessor :card_id

    # PAN of the card
    # @return [String]
    attr_accessor :pan

    # Reference number for tracking of update status request of the specific
    # card,
    # @return [String]
    attr_accessor :move_card_reference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_id'] = 'AccountId'
      @_hash['account_number'] = 'AccountNumber'
      @_hash['card_id'] = 'CardId'
      @_hash['pan'] = 'PAN'
      @_hash['move_card_reference'] = 'MoveCardReference'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_id
        account_number
        card_id
        pan
        move_card_reference
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_id = SKIP, account_number = SKIP, card_id = SKIP,
                   pan = SKIP, move_card_reference = SKIP)
      @account_id = account_id unless account_id == SKIP
      @account_number = account_number unless account_number == SKIP
      @card_id = card_id unless card_id == SKIP
      @pan = pan unless pan == SKIP
      @move_card_reference = move_card_reference unless move_card_reference == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_id = hash.key?('AccountId') ? hash['AccountId'] : SKIP
      account_number = hash.key?('AccountNumber') ? hash['AccountNumber'] : SKIP
      card_id = hash.key?('CardId') ? hash['CardId'] : SKIP
      pan = hash.key?('PAN') ? hash['PAN'] : SKIP
      move_card_reference =
        hash.key?('MoveCardReference') ? hash['MoveCardReference'] : SKIP

      # Create object from extracted values.
      SubmittedMoveCard.new(account_id,
                            account_number,
                            card_id,
                            pan,
                            move_card_reference)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_id: #{@account_id}, account_number: #{@account_number}, card_id:"\
      " #{@card_id}, pan: #{@pan}, move_card_reference: #{@move_card_reference}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_id: #{@account_id.inspect}, account_number:"\
      " #{@account_number.inspect}, card_id: #{@card_id.inspect}, pan: #{@pan.inspect},"\
      " move_card_reference: #{@move_card_reference.inspect}>"
    end
  end
end
