# shell_card_management_ap_is
#
# This file was automatically generated by
# APIMATIC v3.0 ( https://www.apimatic.io ).

module ShellCardManagementApIs
  # UpdateBundleResponse Model.
  class UpdateBundleResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [ErrorStatus]
    attr_accessor :request_action_status

    # TODO: Write general description for this method
    # @return [ErrorStatus]
    attr_accessor :day_time_restriction_status

    # TODO: Write general description for this method
    # @return [ErrorStatus]
    attr_accessor :location_restriction_status

    # TODO: Write general description for this method
    # @return [ErrorStatus]
    attr_accessor :product_restriction_status

    # TODO: Write general description for this method
    # @return [ErrorStatus]
    attr_accessor :usage_restriction_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['request_action_status'] = 'RequestActionStatus'
      @_hash['day_time_restriction_status'] = 'DayTimeRestrictionStatus'
      @_hash['location_restriction_status'] = 'LocationRestrictionStatus'
      @_hash['product_restriction_status'] = 'ProductRestrictionStatus'
      @_hash['usage_restriction_status'] = 'UsageRestrictionStatus'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        request_action_status
        day_time_restriction_status
        location_restriction_status
        product_restriction_status
        usage_restriction_status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(request_action_status = SKIP,
                   day_time_restriction_status = SKIP,
                   location_restriction_status = SKIP,
                   product_restriction_status = SKIP,
                   usage_restriction_status = SKIP)
      @request_action_status = request_action_status unless request_action_status == SKIP
      unless day_time_restriction_status == SKIP
        @day_time_restriction_status =
          day_time_restriction_status
      end
      unless location_restriction_status == SKIP
        @location_restriction_status =
          location_restriction_status
      end
      unless product_restriction_status == SKIP
        @product_restriction_status =
          product_restriction_status
      end
      @usage_restriction_status = usage_restriction_status unless usage_restriction_status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      request_action_status = ErrorStatus.from_hash(hash['RequestActionStatus']) if
        hash['RequestActionStatus']
      day_time_restriction_status = ErrorStatus.from_hash(hash['DayTimeRestrictionStatus']) if
        hash['DayTimeRestrictionStatus']
      location_restriction_status = ErrorStatus.from_hash(hash['LocationRestrictionStatus']) if
        hash['LocationRestrictionStatus']
      product_restriction_status = ErrorStatus.from_hash(hash['ProductRestrictionStatus']) if
        hash['ProductRestrictionStatus']
      usage_restriction_status = ErrorStatus.from_hash(hash['UsageRestrictionStatus']) if
        hash['UsageRestrictionStatus']

      # Create object from extracted values.
      UpdateBundleResponse.new(request_action_status,
                               day_time_restriction_status,
                               location_restriction_status,
                               product_restriction_status,
                               usage_restriction_status)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} request_action_status: #{@request_action_status},"\
      " day_time_restriction_status: #{@day_time_restriction_status}, location_restriction_status:"\
      " #{@location_restriction_status}, product_restriction_status:"\
      " #{@product_restriction_status}, usage_restriction_status: #{@usage_restriction_status}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} request_action_status: #{@request_action_status.inspect},"\
      " day_time_restriction_status: #{@day_time_restriction_status.inspect},"\
      " location_restriction_status: #{@location_restriction_status.inspect},"\
      " product_restriction_status: #{@product_restriction_status.inspect},"\
      " usage_restriction_status: #{@usage_restriction_status.inspect}>"
    end
  end
end
