# shell_card_management_ap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellCardManagementApIs
  # url.
  class UrlEnum
    URL_ENUM = [
      # TODO: Write general description for ENUM_APITESTSHELLCOMTEST
      ENUM_APITESTSHELLCOMTEST = 'api-test.shell.com/test'.freeze,

      # TODO: Write general description for ENUM_APISHELLCOM
      ENUM_APISHELLCOM = 'api.shell.com'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      URL_ENUM.include?(value)
    end
  end
end
